
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=web_app_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      custom_network:
        ipv4_address: 172.20.0.22

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      custom_network:
        ipv4_address: 172.20.0.23

volumes:
  db_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16